sudo: required
services: 
    - docker
before_install:
    - docker build -t acharyajay007/docker-react -f Dockerfile.dev .
script:
    - docker run acharyajay007/docker-react npm run test -- --coverage